version: '1.0'

services:
  php:
    build: .docker/php/
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "80:80"
    command: "tail -f /dev/null"

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - "3306:3306"

